/**
 * Recognised pedigree breeds from The Royal Kennel Club (UK) Breeds A–Z.
 * Source page (downloaded for extraction): https://www.thekennelclub.org.uk/search/breeds-a-to-z/
 * Regenerate: save that page HTML as scripts/kc-breeds-page.html, then run node scripts/extract-kc-breeds.mjs
 */
export const KENNEL_CLUB_BREEDS: readonly string[] = [
  "Affenpinscher",
  "Afghan Hound",
  "Airedale Terrier",
  "Akita",
  "Alaskan Malamute",
  "Anatolian Shepherd Dog",
  "Australian Cattle Dog",
  "Australian Shepherd",
  "Australian Silky Terrier",
  "Australian Terrier",
  "Azawakh (Imp)",
  "Barbet (Imp)",
  "Basenji",
  "Basset Bleu De Gascogne (Imp)",
  "Basset Fauve De Bretagne",
  "Basset Griffon Vendeen (Grand)",
  "Basset Griffon Vendeen (Petit)",
  "Basset Hound",
  "Bavarian Mountain Hound",
  "Beagle",
  "Bearded Collie",
  "Beauceron",
  "Bedlington Terrier",
  "Belgian Shepherd Dog (Groenendael)",
  "Belgian Shepherd Dog (Laekenois)",
  "Belgian Shepherd Dog (Malinois)",
  "Belgian Shepherd Dog (Tervueren)",
  "Bergamasco (Imp)",
  "Bernese Mountain Dog",
  "Bichon Frise",
  "Black & Tan Coonhound (Imp)",
  "Bloodhound",
  "Bolognese",
  "Border Collie",
  "Border Terrier",
  "Borzoi",
  "Boston Terrier",
  "Bouvier Des Flandres",
  "Boxer",
  "Bracco Italiano",
  "Braque D&#x2019;Auvergne (Imp)",
  "Briard",
  "Brittany",
  "Bull Terrier",
  "Bull Terrier (Miniature)",
  "Bulldog",
  "Bullmastiff",
  "Cairn Terrier",
  "Canaan Dog",
  "Canadian Eskimo Dog",
  "Catalan Sheepdog",
  "Cavalier King Charles Spaniel",
  "Cesky Terrier",
  "Chihuahua (Long Coat)",
  "Chihuahua (Smooth Coat)",
  "Chinese Crested",
  "Chow Chow",
  "Cirneco Dell&#x27;Etna",
  "Collie (Rough)",
  "Collie (Smooth)",
  "Coton De Tulear",
  "Dachshund (Long Haired)",
  "Dachshund (Miniature Long Haired)",
  "Dachshund (Miniature Smooth Haired)",
  "Dachshund (Miniature Wire Haired)",
  "Dachshund (Smooth Haired)",
  "Dachshund (Wire Haired)",
  "Dalmatian",
  "Dandie Dinmont Terrier",
  "Deerhound",
  "Dobermann",
  "Dogue de Bordeaux",
  "English Setter",
  "English Toy Terrier (Black & Tan)",
  "Entlebucher Mountain Dog (Imp)",
  "Estrela Mountain Dog",
  "Eurasier",
  "Finnish Lapphund",
  "Finnish Spitz",
  "Fox Terrier (Smooth)",
  "Fox Terrier (Wire)",
  "Foxhound",
  "French Bulldog",
  "German Longhaired Pointer",
  "German Pinscher",
  "German Shepherd Dog",
  "German Shorthaired Pointer",
  "German Spitz (Klein)",
  "German Spitz (Mittel)",
  "German Wirehaired Pointer",
  "Giant Schnauzer",
  "Glen Of Imaal Terrier",
  "Gordon Setter",
  "Grand Bleu De Gascogne (Imp)",
  "Great Dane",
  "Great Swiss Mountain Dog",
  "Greenland Dog",
  "Greyhound",
  "Griffon Bruxellois",
  "Griffon Fauve De Bretagne (Imp)",
  "Hamiltonstovare",
  "Harrier",
  "Havanese",
  "Hovawart",
  "Hungarian Kuvasz (Imp)",
  "Hungarian Mudi (Imp)",
  "Hungarian Puli",
  "Hungarian Pumi",
  "Hungarian Vizsla",
  "Hungarian Wirehaired Vizsla",
  "Ibizan Hound",
  "Icelandic Sheepdog (Imp)",
  "Irish Red & White Setter",
  "Irish Setter",
  "Irish Terrier",
  "Irish Wolfhound",
  "Italian Greyhound",
  "Italian Spinone",
  "Jack Russell Terrier",
  "Japanese Akita Inu",
  "Japanese Chin",
  "Japanese Shiba Inu",
  "Japanese Spitz",
  "Keeshond",
  "Kerry Blue Terrier",
  "King Charles Spaniel",
  "Komondor",
  "Kooikerhondje",
  "Korean Jindo (Imp)",
  "Korthals Griffon (Imp)",
  "Lagotto Romagnolo",
  "Lakeland Terrier",
  "Lancashire Heeler",
  "Large Munsterlander",
  "Leonberger",
  "Lhasa Apso",
  "Lowchen (Little Lion Dog)",
  "Maltese",
  "Manchester Terrier",
  "Maremma Sheepdog",
  "Mastiff",
  "Miniature Pinscher",
  "Miniature Schnauzer",
  "Neapolitan Mastiff",
  "Newfoundland",
  "Norfolk Terrier",
  "Norwegian Buhund",
  "Norwegian Elkhound",
  "Norwich Terrier",
  "Old English Sheepdog",
  "Otterhound",
  "Papillon",
  "Parson Russell Terrier",
  "Pekingese",
  "Pharaoh Hound",
  "Picardy Sheepdog (Imp)",
  "Pointer",
  "Polish Hunting Dog (Imp)",
  "Polish Lowland Sheepdog",
  "Pomeranian",
  "Poodle (Miniature)",
  "Poodle (Standard)",
  "Poodle (Toy)",
  "Portuguese Podengo",
  "Portuguese Pointer (Imp)",
  "Portuguese Water Dog",
  "Pug",
  "Pyrenean Mastiff (Imp)",
  "Pyrenean Mountain Dog",
  "Pyrenean Sheepdog (Long Haired)",
  "Pyrenean Sheepdog (Smooth Faced) (Imp)",
  "Retriever (Chesapeake Bay)",
  "Retriever (Curly Coated)",
  "Retriever (Flat Coated)",
  "Retriever (Golden)",
  "Retriever (Labrador)",
  "Retriever (Nova Scotia Duck Tolling)",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Russian Black Terrier",
  "Russian Toy",
  "Saluki",
  "Samoyed",
  "Schipperke",
  "Schnauzer",
  "Scottish Terrier",
  "Sealyham Terrier",
  "Shar Pei",
  "Shetland Sheepdog",
  "Shih Tzu",
  "Siberian Husky",
  "Skye Terrier",
  "Sloughi",
  "Slovakian Rough Haired Pointer (Imp)",
  "Small Munsterlander (Imp)s",
  "Soft Coated Wheaten Terrier",
  "Spaniel (American Cocker)",
  "Spaniel (American Water) (Imp)",
  "Spaniel (Clumber)",
  "Spaniel (Cocker)",
  "Spaniel (English Springer)",
  "Spaniel (Field)",
  "Spaniel (Irish Water)",
  "Spaniel (Sussex)",
  "Spaniel (Welsh Springer)",
  "Spanish Water Dog",
  "St. Bernard",
  "Staffordshire Bull Terrier",
  "Swedish Lapphund (Imp)",
  "Swedish Vallhund",
  "Tibetan Mastiff",
  "Tibetan Spaniel",
  "Tibetan Terrier",
  "Turkish Kangal Dog",
  "Weimaraner",
  "Welsh Corgi (Cardigan)",
  "Welsh Corgi (Pembroke)",
  "Welsh Terrier",
  "West Highland White Terrier",
  "Whippet",
  "White Swiss Shepherd Dog (Imp)",
  "Xoloitzcuintle (Mex Hairless) Int (Imp)",
  "Xoloitzcuintle (Mex Hairless) Min (Imp)",
  "Xoloitzcuintle (Mex Hairless) Std (Imp)",
  "Yorkshire Terrier",
];

/** Full dropdown list: KC breeds, then non-pedigree options. */
export const DOG_BREED_OPTIONS: readonly string[] = [
  "Mixed breed",
  "Other",
  ...KENNEL_CLUB_BREEDS,
];
